name: Setup Node.js and pnpm
description: Setup Node.js, pnpm with caching

inputs:
  node-version:
    description: Node.js version
    required: false
    default: '22'
  pnpm-version:
    description: pnpm version
    required: false
    default: '10'
  registry-url:
    description: npm registry URL
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v5
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm
        registry-url: ${{ inputs.registry-url }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
